superkernel:
  input_image_size: 112
  superkernel_embedding_dim: 96
  superkernel_depth: 0
  superkernel_heads: 8
  superkernel_layer_type: linear
  superkernel_kernel_size: 1
  mlp_ratio: 4

encoder:
    layers_blocks: [2, 2, 2]
    embedding_dims: [192, 384, 768]
    channel_embedding_dim: 96
    include_stem: true

decoder:
  decoded_embed_dim: 512
  input_embedding_dim: 768
  num_blocks: 1
  scaling_factor: 8

device: cuda:3
num_workers: 4
batch_size: 1
lr: 5e-4
final_lr: 1e-6
weight_decay: 0.0001
gradient_accumulation_steps: 1
epochs: 500
num_warmup_steps: 200
num_annealing_steps: 400000
min_channels: 20
loss_reduction: mean
tags: ['ConvNext', 'Zero superkernel', 'Gaussian NLL',]
